DROP TABLE IF EXISTS aka_names;
DROP TABLE IF EXISTS actors;
DROP TABLE IF EXISTS aka_titles;
DROP TABLE IF EXISTS acted_in;
DROP TABLE IF EXISTS movies;
DROP TABLE IF EXISTS series;
DROP TABLE IF EXISTS movies_genres;
DROP TABLE IF EXISTS genres;
DROP TABLE IF EXISTS keywords;
DROP TABLE IF EXISTS movies_keywords;

